name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered"

      - name: Slack Notification Triggered
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Greetings!"
      
      - run: echo "Workflow finished"

